"""
chat/pdf_generator.py — Server-side PDF generation using fpdf2.

Generates clean, single-document PDFs in Standard or APA format.
No imports from existing LabOS modules.
"""

from datetime import datetime
from typing import List

from fpdf import FPDF


def _sanitize(text: str) -> str:
    """Replace Unicode characters that aren't supported by standard PDF fonts."""
    replacements = {
        "\u2013": "-",   # en-dash
        "\u2014": "--",  # em-dash
        "\u2018": "'",   # left single quote
        "\u2019": "'",   # right single quote
        "\u201c": '"',   # left double quote
        "\u201d": '"',   # right double quote
        "\u2022": "-",   # bullet
        "\u2026": "...", # ellipsis
        "\u2265": ">=",  # ≥
        "\u2264": "<=",  # ≤
        "\u00b7": "-",   # middle dot
        "\u2010": "-",   # hyphen
        "\u2011": "-",   # non-breaking hyphen
        "\u2012": "-",   # figure dash
        "\u00a0": " ",   # non-breaking space
        "\u200b": "",    # zero-width space
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    # Strip any remaining non-latin1 characters
    return text.encode("latin-1", errors="replace").decode("latin-1")


def generate_pdf(
    title: str,
    confidence_level: str,
    sections: List[dict],
    action_items: List[str],
    caveats: List[str],
    fmt: str = "standard",
) -> bytes:
    """
    Generate a PDF document and return it as bytes.

    Args:
        title: Document title.
        confidence_level: "High", "Moderate", or "Low".
        sections: List of {"heading": str, "body": str} dicts.
        action_items: List of action item strings.
        caveats: List of caveat strings.
        fmt: "standard" or "apa".

    Returns:
        PDF file content as bytes.
    """
    if fmt == "apa":
        return _generate_apa(title, confidence_level, sections, action_items, caveats)
    return _generate_standard(title, confidence_level, sections, action_items, caveats)


def _generate_standard(
    title: str,
    confidence_level: str,
    sections: List[dict],
    action_items: List[str],
    caveats: List[str],
) -> bytes:
    """Standard LabOS format — clean, professional."""
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 12, _sanitize(title), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # Meta line
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(120, 120, 120)
    date_str = datetime.now().strftime("%B %d, %Y")
    pdf.cell(0, 6, f"Generated by LabOS Multi-Agent Research Engine  |  {date_str}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # Confidence badge
    if confidence_level:
        pdf.set_font("Helvetica", "B", 10)
        if confidence_level == "High":
            pdf.set_text_color(6, 95, 70)
        elif confidence_level == "Moderate":
            pdf.set_text_color(146, 64, 14)
        else:
            pdf.set_text_color(153, 27, 27)
        pdf.cell(0, 8, f"Confidence: {confidence_level}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

    # Divider
    pdf.set_draw_color(212, 168, 67)
    pdf.set_line_width(0.5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    # Sections
    for section in sections:
        heading = section.get("heading", "")
        body = section.get("body", "")
        if not body:
            continue

        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(180, 140, 50)
        pdf.cell(0, 8, heading.upper(), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(30, 30, 30)
        pdf.multi_cell(0, 5.5, _sanitize(body))
        pdf.ln(4)

    # Action Items
    if action_items:
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(180, 140, 50)
        pdf.cell(0, 8, "ACTION ITEMS", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(30, 30, 30)
        for item in action_items:
            pdf.cell(5)
            pdf.multi_cell(0, 5.5, f"-  {_sanitize(item)}")
            pdf.ln(1)
        pdf.ln(3)

    # Caveats
    if caveats:
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(180, 140, 50)
        pdf.cell(0, 8, "CAVEATS", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(30, 30, 30)
        for caveat in caveats:
            pdf.cell(5)
            pdf.multi_cell(0, 5.5, f"-  {_sanitize(caveat)}")
            pdf.ln(1)

    return pdf.output()


def _generate_apa(
    title: str,
    confidence_level: str,
    sections: List[dict],
    action_items: List[str],
    caveats: List[str],
) -> bytes:
    """APA 7th Edition format — Times New Roman, double-spaced, centered headings."""
    pdf = FPDF()
    left_margin = 25.4   # 1 inch
    right_margin = 25.4  # 1 inch
    pdf.set_auto_page_break(auto=True, margin=25.4)
    pdf.set_left_margin(left_margin)
    pdf.set_right_margin(right_margin)
    pdf.add_page()

    page_w = pdf.w  # 210mm for A4
    content_w = page_w - left_margin - right_margin  # usable width
    indent = 12.7  # 0.5 inch APA indent
    indented_w = content_w - indent

    line_h = 6.8  # ~double spacing at 12pt

    # Title page elements (centered)
    pdf.ln(30)
    pdf.set_font("Times", "B", 12)
    pdf.cell(0, line_h, _sanitize(title), align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(line_h)

    pdf.set_font("Times", "", 12)
    pdf.cell(0, line_h, "LabOS Multi-Agent Research Engine", align="C", new_x="LMARGIN", new_y="NEXT")

    date_str = datetime.now().strftime("%B %d, %Y")
    pdf.cell(0, line_h, date_str, align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(line_h)

    if confidence_level:
        pdf.set_font("Times", "B", 12)
        pdf.cell(0, line_h, f"Confidence Level: {confidence_level}", align="C", new_x="LMARGIN", new_y="NEXT")

    # Start content on new page
    pdf.add_page()

    # Sections
    for section in sections:
        heading = section.get("heading", "")
        body = section.get("body", "")
        if not body:
            continue

        # Level 1 heading: centered, bold
        pdf.set_font("Times", "B", 12)
        pdf.cell(0, line_h, _sanitize(heading), align="C", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(line_h * 0.5)

        # Body: indented first line, double-spaced
        pdf.set_font("Times", "", 12)
        paragraphs = body.split("\n\n") if "\n\n" in body else body.split("\n")
        for para in paragraphs:
            para = para.strip()
            if not para:
                continue
            # Move x to indent position, then use explicit width
            pdf.set_x(left_margin + indent)
            pdf.multi_cell(indented_w, line_h, _sanitize(para))
            pdf.ln(line_h * 0.3)

    # Action Items
    if action_items:
        pdf.set_font("Times", "B", 12)
        pdf.cell(0, line_h, "Action Items", align="C", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(line_h * 0.5)
        pdf.set_font("Times", "", 12)
        for item in action_items:
            pdf.set_x(left_margin + indent)
            pdf.multi_cell(indented_w, line_h, f"-  {_sanitize(item)}")
        pdf.ln(line_h)

    # Caveats
    if caveats:
        pdf.set_font("Times", "B", 12)
        pdf.cell(0, line_h, "Caveats", align="C", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(line_h * 0.5)
        pdf.set_font("Times", "", 12)
        for caveat in caveats:
            pdf.set_x(left_margin + indent)
            pdf.multi_cell(indented_w, line_h, f"-  {_sanitize(caveat)}")

    return pdf.output()
